# Generated by Django 5.0.1 on 2024-01-17 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('tipo_documento', models.CharField(choices=[('CEDULA', 'Cedula'), ('NIT', 'NIT')], default='Cedula', max_length=10)),
                ('numero_documento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_cumpleanos', models.DateField(blank=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mpago',
            fields=[
                ('id_mpago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('BOUQUET', 'Bouquet de Globos')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('tipo_documento', models.CharField(choices=[('CEDULA', 'Cedula'), ('NIT', 'NIT')], default='Cedula', max_length=10)),
                ('numero_documento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('nombre_cuenta', models.CharField(blank=True, max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(blank=True, choices=[('en_curso', 'En Curso'), ('terminado', 'Terminado')], default='en_curso', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasaparty.cliente')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='InventarioPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('asignado', models.BooleanField(default=False, editable=False)),
                ('evento_alquilado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_propio_rel', to='kasaparty.evento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='inventario_propio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_inventario_propio', to='kasaparty.inventariopropio'),
        ),
        migrations.CreateModel(
            name='InventarioProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('asignado', models.BooleanField(default=False, editable=False)),
                ('fecha_salida', models.DateField(auto_now=True)),
                ('evento_alquilado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_proveedor_rel', to='kasaparty.evento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasaparty.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='inventario_proveedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_inventario_proveedor', to='kasaparty.inventarioproveedor'),
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasaparty.componente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasaparty.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cotizacion', models.DateField(auto_now_add=True)),
                ('fecha_evento', models.DateField()),
                ('validez_dias', models.PositiveIntegerField(default=7)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasaparty.cliente')),
                ('productos', models.ManyToManyField(to='kasaparty.producto')),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasaparty.producto'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kasaparty.evento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasaparty.tematica'),
        ),
    ]
