# Generated by Django 5.0.1 on 2024-01-17 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioproveedor',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='inventarioproveedor',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='inventariopropio',
            name='evento_alquilado_anterior',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kasaparty.evento'),
        ),
        migrations.AddField(
            model_name='inventarioproveedor',
            name='evento_alquilado_anterior',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kasaparty.evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(blank=True, choices=[('en_curso', 'En Curso'), ('terminado', 'Terminado')], default='en_curso', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='inventariopropio',
            name='evento_alquilado',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_propio_rel', to='kasaparty.evento'),
        ),
        migrations.AlterField(
            model_name='inventarioproveedor',
            name='evento_alquilado',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_proveedor_rel', to='kasaparty.evento'),
        ),
    ]
