# Generated by Django 5.0.1 on 2024-01-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0002_remove_inventarioproveedor_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='anticipo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kasaparty.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.IntegerField(),
        ),
    ]
