# Generated by Django 5.0.1 on 2024-01-17 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0003_reserva_anticipo_reserva_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cotizacion',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='kasaparty.cotizacion'),
            preserve_default=False,
        ),
    ]
