# Generated by Django 5.0.1 on 2024-01-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0005_alter_cliente_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
    ]
