# Generated by Django 5.0.1 on 2024-01-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0006_alter_cotizacion_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='validez_dias',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
