# Generated by Django 5.0.1 on 2024-01-15 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0006_alter_inventario_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioproveedor',
            name='asignado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='inventarioproveedor',
            name='disponible',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='inventarioproveedor',
            name='evento_alquilado',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_proveedor_evento_alquilado', to='kasaparty.evento'),
        ),
        migrations.AlterField(
            model_name='inventarioproveedor',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
    ]
