# Generated by Django 5.0.1 on 2024-01-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0007_inventarioproveedor_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='disponible',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='inventarioproveedor',
            name='disponible',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', editable=False, max_length=2),
        ),
    ]
