# Generated by Django 5.0.1 on 2024-01-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0007_alter_cotizacion_validez_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
