# Generated by Django 5.0.1 on 2024-01-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0008_alter_inventario_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='terminado',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', editable=False, max_length=2),
        ),
    ]
