# Generated by Django 5.0.1 on 2024-01-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0009_alter_evento_terminado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='terminado',
            new_name='estado',
        ),
    ]
