# Generated by Django 5.0.1 on 2024-01-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0009_alter_reserva_monto_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='monto_total',
            new_name='total',
        ),
    ]
