# Generated by Django 5.0.1 on 2024-01-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0010_rename_terminado_evento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='estado',
        ),
        migrations.AddField(
            model_name='evento',
            name='en_curso',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
