# Generated by Django 5.0.1 on 2024-01-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0010_rename_monto_total_reserva_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='anticipo',
            field=models.IntegerField(blank=True),
        ),
    ]
