# Generated by Django 5.0.1 on 2024-01-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0011_alter_reserva_anticipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='total',
            new_name='pendiente',
        ),
    ]
