# Generated by Django 5.0.1 on 2024-01-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0011_remove_evento_estado_evento_en_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='en_curso',
            field=models.BooleanField(default=True),
        ),
    ]
