# Generated by Django 5.0.1 on 2024-01-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0012_alter_evento_en_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='en_curso',
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('en_curso', 'En Curso'), ('terminado', 'Terminado')], default='en_curso', editable=False, max_length=10),
        ),
    ]
