# Generated by Django 5.0.1 on 2024-01-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0013_remove_evento_en_curso_evento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('en_curso', 'En Curso'), ('terminado', 'Terminado')], default='en_curso', max_length=10),
        ),
    ]
