# Generated by Django 5.0.1 on 2024-01-16 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0015_remove_inventario_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(blank=True, choices=[('en_curso', 'En Curso'), ('terminado', 'Terminado')], default='en_curso', max_length=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inventario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kasaparty.inventario'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tematica',
            field=models.ManyToManyField(blank=True, to='kasaparty.tematica'),
        ),
    ]
