# Generated by Django 5.0.1 on 2024-01-16 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0016_alter_evento_descripcion_alter_evento_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='inventario_proveedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kasaparty.inventarioproveedor'),
        ),
    ]
