# Generated by Django 5.0.1 on 2024-01-16 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0017_alter_evento_inventario_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasaparty.inventario'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inventario_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasaparty.inventarioproveedor'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tematica',
            field=models.ManyToManyField(to='kasaparty.tematica'),
        ),
    ]
