# Generated by Django 5.0.1 on 2024-01-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0018_alter_evento_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='asignado',
            field=models.BooleanField(editable=False),
        ),
    ]
