# Generated by Django 5.0.1 on 2024-01-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasaparty', '0019_alter_inventario_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='asignado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
